# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c834f091f19ce2d1ef1bf46d27fbb0b14d1f07ddbb2e1fe0206794a3a64bb3746bef79d4d4b296d13e6f51eb70fa3f741c9be5e664a82f9104681d3c409a5a9

test:
  secret_key_base: 1d217d7d056ce2f3eec5953a502464aa252ff171826a80f1755be116d84a843825d7ac7309210e9bef40aab436c857b99818d0739f686b412e525dacedf1355e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
